name: maquinaJava

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: Comprobar código del repositorio
        uses: actions/checkout@v3

      - name: Instalar Docker y Docker Compose en la EC2
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.IP_SERVER }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.PRIVATE_KEY }}
          port: ${{ secrets.PORT }}
          script: |
            # Instalar Docker si no existe
            if ! command -v docker &> /dev/null; then
              echo "Instalando Docker..."
              sudo apt update
              sudo apt install -y docker.io
              sudo systemctl enable docker
              sudo systemctl start docker
              sudo usermod -aG docker $USER
            else
              echo "Docker ya está instalado"
            fi

            # Instalar Docker Compose si no existe
            if ! command -v docker-compose &> /dev/null; then
              echo "Instalando Docker Compose..."
              sudo curl -L "https://github.com/docker/compose/releases/download/v2.24.7/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
              sudo chmod +x /usr/local/bin/docker-compose
            else
              echo "Docker Compose ya está instalado"
            fi

      - name: Crear carpeta de despliegue en EC2
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.IP_SERVER }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.PRIVATE_KEY }}
          port: ${{ secrets.PORT }}
          script: |
            mkdir -p /home/ubuntu/fs1001

      - name: Sincronizar archivos con el servidor
        uses: burnett01/rsync-deployments@7.0.2
        with:
          switches: "-avz --delete"
          path: "./"
          remote_host: ${{ secrets.IP_SERVER }}
          remote_user: ${{ secrets.USERNAME }}
          remote_path: "/home/ubuntu/fs1001/"
          remote_key: ${{ secrets.PRIVATE_KEY }}
          remote_port: ${{ secrets.PORT }}

      - name: Levantar contenedores con Docker Compose
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.IP_SERVER }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.PRIVATE_KEY }}
          port: ${{ secrets.PORT }}
          script: |
            cd /home/ubuntu/fs1001/
            sudo docker compose down || true
            sudo docker compose up -d --build
